remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-sitemap

url: "https://sparrowfabrications.co.uk"
show_downloads: false
title: Sparrow Fabrications
description: FDM 3D Printed Camera Accessories made in the U.K.
github:
  is_project_page: false
email_address: "info@sparrowfabrications.co.uk"
ebay_uk_url: "https://www.ebay.co.uk/usr/sparrowfabrications"
ebay_us_url: "https://www.ebay.com/sch/i.html?_dkr=1&iconV2Request=true&_blrs=recall_filtering&_ssn=sparrowfabrications&_oac=1&_dmd=2&_fcid=1&LH_PrefLoc=2&LH_All=1"
etsy_url: "https://sparrowfabrications.etsy.com"
amazon_cable_url: "https://www.amazon.co.uk/dp/B09126NKPN"
amazon_30mm_step_up_ring_url: "https://amzn.eu/d/0el9paj"
amazon_37mm_step_up_ring_url: "https://amzn.eu/d/hoxeejY"
amazon_43mm_step_up_ring_url: "https://amzn.eu/d/880WBJt"
kaiser_6109_url: "https://www.kaiser-fototechnik.de/en/produkte/artikel.php?nr=6109"
